.Dd December 2017
.Dt domainname 1
.Os
.Sh NAME
.Nm domainname
.Nd set or write the current domain name
.Sh SYNOPSIS
.Nm
.Op Ar name
.Sh DESCRIPTION
.Nm
writes the current domain name to the standard output.
The super-user can set the domain name by giving an argument.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr hostname 1 ,
.Xr getdomainname 3 ,
.Xr setdomainname 3
