.Dd December 2017
.Dt hostname 1
.Os
.Sh NAME
.Nm hostname
.Nd set or write the current host name
.Sh SYNOPSIS
.Nm
.Op Ar name
.Sh DESCRIPTION
.Nm
writes the current host name to the standard output.
The super-user can set the host name by giving an argument.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr domainname 1 ,
.Xr gethostname 3 ,
.Xr sethostname 3 ,
.Xr hostname 7
