.Dd March 03, 2018
.Dt LINK 1
.Os
.Sh NAME
.Nm link
.Nd call link function
.Sh SYNOPSIS
.Nm
.Ar source
.Ar target
.Sh DESCRIPTION
.Nm
performs the function call
.Fn link source target .
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr ln 1 ,
.Xr link 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
