.Dd March 03, 2018
.Dt LOGNAME 1
.Os
.Sh NAME
.Nm logname
.Nd return the user's login name
.Sh SYNOPSIS
.Nm logname
.Sh DESCRIPTION
.Nm
writes the user's login name to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr who 1 ,
.Xr whoami 1 ,
.Xr getlogin 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
