.Dd March 03, 2018
.Dt SLEEP 1
.Os
.Sh NAME
.Nm sleep
.Nd suspend execution for an interval
.Sh SYNOPSIS
.Nm
time
.Sh DESCRIPTION
.Nm
suspends execution for
.Ar time
seconds.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr sleep 3
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
