.Dd March 03, 2018
.Dt time 1
.Os
.Sh NAME
.Nm time
.Nd time a simple command
.Sh SYNOPSIS
.Nm
.Op Fl p
.Ar command
.Op Ar argument ...
.Sh DESCRIPTION
.Nm
runs
.Ar command
and writes the real time, user time and system time, in seconds, to the
standard error.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl p
Ignored.
.El
.Sh EXIT STATUS
The
.Nm
utility exits with one of the following values:
.Pp
.Bl -tag -width indent -offset indent -compact
.It 1\-125
An error occured.
.It 126
The
.Ar command
was found but could not be invoked.
.It 127
The
.Ar command
could not be found.
.El
.Pp
Otherwise, the exit status of
.Nm
will be that of
.Ar command .
.Sh SEE ALSO
.Xr times 2 ,
.Xr waitpid 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
