.Dd March 03, 2018
.Dt UNLINK 1
.Os
.Sh NAME
.Nm unlink
.Nd call the unlink function
.Sh SYNOPSIS
.Nm
.Ar file
.Sh DESCRIPTION
.Nm
performs the function call
.Fn unlink file .
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr rm 1 ,
.Xr rmdir 1 ,
.Xr unlink 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
